# Generated by Django 3.2.22 on 2024-01-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('category_id', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('currency_id', models.CharField(max_length=50)),
            ],
        ),
    ]
