# Generated by Django 3.2.22 on 2024-01-16 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metodoPago', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(max_length=255)),
                ('payment_type', models.CharField(max_length=255)),
                ('merchant_order_id', models.CharField(max_length=255)),
                ('fecha_transaccion', models.DateField()),
                ('hora_transaccion', models.TimeField()),
                ('id_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metodoPago.planpago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
