# Generated by Django 3.2.22 on 2024-01-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodoPago', '0002_registrotransaccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
    ]
