# Generated by Django 4.2.6 on 2024-03-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metodoPago', '0003_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpago',
            name='alumnos',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
