# Generated by Django 4.2.6 on 2023-10-24 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_texto', models.TextField(blank=True, null=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SurveyApp.pregunta')),
                ('respuesta_opcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SurveyApp.opcionmultiple')),
            ],
        ),
        migrations.DeleteModel(
            name='RespuestaUsuario',
        ),
    ]
