# Generated by Django 4.2.6 on 2023-10-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyApp', '0002_respuestaalumno_delete_respuestausuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcionmultiple',
            name='puntaje',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='tipo_pregunta',
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='texto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='respuestaalumno',
            name='respuesta_texto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
