# Generated by Django 4.2.6 on 2023-10-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyApp', '0003_remove_opcionmultiple_puntaje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='texto',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tipo_pregunta',
            field=models.CharField(choices=[('OPC', 'Opción Múltiple'), ('TXT', 'Texto')], default='OPC', max_length=3),
        ),
    ]
