# Generated by Django 4.2.6 on 2023-10-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyApp', '0004_remove_pregunta_texto_pregunta_tipo_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='texto',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
