# Generated by Django 4.2.6 on 2023-10-24 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyApp', '0005_pregunta_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaalumno',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_alumnos', to='SurveyApp.pregunta'),
        ),
    ]
