# Generated by Django 4.2.6 on 2023-10-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyApp', '0007_answer_question_remove_respuestaalumno_pregunta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
