# Generated by Django 4.2.6 on 2023-10-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyApp', '0008_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='option_answer',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_answer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
