# Generated by Django 4.2.6 on 2023-10-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyApp', '0009_alter_answer_option_answer_alter_answer_text_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
