# Generated by Django 4.2.6 on 2023-10-26 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyApp', '0010_editquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditQuestion',
        ),
    ]
