# Generated by Django 4.2.6 on 2023-10-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyApp', '0011_delete_editquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
