# Generated by Django 4.2.6 on 2023-10-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyApp', '0012_alter_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
