# Generated by Django 4.2.6 on 2023-11-14 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyApp', '0015_answer_porcentaje_alter_answer_id_alter_question_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='porcentaje',
        ),
    ]
