# Generated by Django 4.2.6 on 2024-03-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyApp', '0016_remove_answer_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='factor_kabasis',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
