# Generated by Django 4.2.6 on 2024-03-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyApp', '0017_question_factor_kabasis'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntaje',
            name='porcentaje_actitud',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='puntaje',
            name='porcentaje_conducta',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='puntaje',
            name='porcentaje_conocimientos',
            field=models.IntegerField(null=True),
        ),
    ]
