# Generated by Django 4.2.6 on 2024-03-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyApp', '0018_puntaje_porcentaje_actitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='dimension_kabasis',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='item_kabasis',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
