# Generated by Django 4.2.6 on 2024-03-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyApp', '0019_question_dimension_kabasis_question_item_kabasis'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntaje',
            name='porcentaje_compromiso',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='puntaje',
            name='porcentaje_contrasena',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='puntaje',
            name='porcentaje_correos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='puntaje',
            name='porcentaje_denuncia',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='puntaje',
            name='porcentaje_disuasion',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='puntaje',
            name='porcentaje_entrenamiento',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='puntaje',
            name='porcentaje_hackers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='puntaje',
            name='porcentaje_navegar',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='puntaje',
            name='porcentaje_politicas',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='puntaje',
            name='porcentaje_riesgos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='puntaje',
            name='porcentaje_seg_computador',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='puntaje',
            name='porcentaje_seg_exterior',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='puntaje',
            name='porcentaje_sitios_seg',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='puntaje',
            name='porcentaje_virus',
            field=models.IntegerField(null=True),
        ),
    ]
