# Generated by Django 4.2.6 on 2024-01-30 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos')),
                ('descripcion', models.TextField(max_length=500)),
                ('orden', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Progreso',
                'verbose_name_plural': 'Progresos',
            },
        ),
        migrations.CreateModel(
            name='QuizContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('orden', models.PositiveIntegerField(null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.curso')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='unidades')),
                ('descripcion', models.TextField()),
                ('orden', models.PositiveIntegerField()),
                ('margen_izquierdo', models.IntegerField(default=0)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('video_url', models.URLField()),
                ('descripcion', models.TextField()),
                ('orden', models.PositiveIntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.curso')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.unidadcurso')),
            ],
        ),
        migrations.CreateModel(
            name='QuizProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=0, max_digits=5)),
                ('aprobado', models.BooleanField(default=False)),
                ('progreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.progreso')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.quizcontent')),
            ],
            options={
                'unique_together': {('progreso', 'quiz')},
            },
        ),
        migrations.AddField(
            model_name='quizcontent',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.unidadcurso'),
        ),
        migrations.CreateModel(
            name='QuestionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('option', 'Opción múltiple'), ('text', 'Texto')], max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('option_a', models.CharField(max_length=255, null=True)),
                ('option_b', models.CharField(max_length=255, null=True)),
                ('option_c', models.CharField(max_length=255, null=True)),
                ('option_d', models.CharField(max_length=255, null=True)),
                ('correct_answer', models.CharField(max_length=1)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.quizcontent')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField(default=False)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.unidadcurso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='progreso',
            name='quizzes_completados',
            field=models.ManyToManyField(blank=True, through='CursosApp.QuizProgreso', to='CursosApp.quizcontent'),
        ),
        migrations.AddField(
            model_name='progreso',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.unidadcurso'),
        ),
        migrations.AddField(
            model_name='progreso',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progreso',
            name='videos_vistos',
            field=models.ManyToManyField(blank=True, to='CursosApp.video'),
        ),
        migrations.CreateModel(
            name='AnswerContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text_answer', models.CharField(max_length=255, null=True)),
                ('option_answer', models.CharField(max_length=1, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CursosApp.questioncontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='progreso',
            unique_together={('user', 'unidad')},
        ),
    ]
