# Generated by Django 4.2.6 on 2024-01-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CursosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizprogreso',
            name='porcentaje',
            field=models.DecimalField(decimal_places=0, max_digits=5, null=True),
        ),
    ]
