# Generated by Django 4.2.6 on 2024-02-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CursosApp', '0003_quizprogreso_intentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncontent',
            name='explicacion_correct',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
